mac:
	GOOS=darwin GOARCH=amd64 go build -o ../bin/darwin-amd64/tui-select ./tui-select.go
linux:
	GOOS=linux GOARCH=amd64 go build -o ../bin/linux-amd64/tui-select ./tui-select.go
win:
	GOOS=windows GOARCH=amd64 go build -o ../bin/win-amd64/tui-select.exe ./tui-select.go
	GOOS=windows GOARCH=386 go build -o ../bin/win-386/tui-select.exe ./tui-select.go
